version: '3.8'
services:
  web:
    build: .
    ports:
      - "5005:5000"
    environment:
      FLASK_ENV: production  # Change FLASK_ENV to production for production environment
    volumes:
      - .:/app
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app  # Use Gunicorn as a WSGI HTTP server
    scale: 3  # Scale the "web" service to 3 instances

